### ISSUE TITLE
Android behaviour on Samsung Galaxy

### ISSUE THREAD

**Issue by desmondhume** [Andr3wHur5t/react-native-keyboard-spacer#44] opened 2016-12-20 13:44 UTC
Hi, the package works great both on android and ios, but it acts weirdly on samsung devices. 
Basically, it seems like `<KeyboardSpacer />` is not needed on samsung devices, while necessary on other android devices to move the content away from keyboard. 

Eg. I have a `position: absolute` element anchored to the bottom of the view, and I'm using a keyboardspacer to keep it attached to the bottom and visible right above the keyboard when the keyboard shows up. If I use the keyboard spacer, it looks right on my Nexus 5, but it pushes the button away from the keyboard on a Samsung Galaxy S6.

The only solution I came up with is device detection, but I don't think it's a viable solution (I should test every possible android device to ensure the same behaviour).

Has anyone experienced this same inconsistency?

**Comment by hanefi** [comment] 2016-12-27 12:11
I tested my app only with galaxy phones. So what I did was 
```
Platform.select({ios: <KeyboardSpacer/>, android: null})
```

This results in the intended behaviour on IOS and my galaxy phones and galaxy tablets. Now I checked Nexus 5 on simulator and it looks fine on that device as well.

BTW, I an running on 0.32

**Comment by tafelito** [comment] 2016-12-29 17:31
I tried @hanefi solution and it works great! The only problem I see is that if you have a listview and a navbar (or a view acting as a custom navbar like I have) is that on a samsung galaxy it pushes all the components up, not only the listview. Where in other devices like ios, the nabvar stays there and only pushes the listview up. Are you experiencing the same behavior in yours?

**Comment by hanefi** [comment] 2016-12-30 10:28
Hi @tafelito, 

I am using [React Native router Flux](https://github.com/aksonov/react-native-router-flux/) for navbars and I do not have this problem. The NavBar is still there in both IOS and Android when the keyboard appears.

I do not really like [React Native router Flux](https://github.com/aksonov/react-native-router-flux/) though. There are some limitations that keeps bugging me. I do not really recommend you start using it

**Comment by tafelito** [comment] 2016-12-30 15:18
Yes I'm using React Native router Flux too and I'm not a big fan too. Because the navbar it's not very customizable, it's not always enough. So sometimes I use a custom navbar (it's actually a regular view that fulfills the same purpose as the navbar with different styles or some extra functionality)

 I'll probably do the switch anyways when the new ExNavigation 2 whenever it comes out

So I solved this by adding `android:windowSoftInputMode="adjustResize"` in the Android Manifest

Thanks for your feedback

**Comment by Andr3wHur5t** [comment] 2017-03-03 07:35
Closing as this seems resolved;

**Closed as completed by Andr3wHur5t** 2017-03-03 07:35 UTC
